
btn_to_register_id = 'com.loginmodule.learning:id/textViewLinkRegister'
input_name_id = 'com.loginmodule.learning:id/textInputEditTextName'
input_email_id = 'com.loginmodule.learning:id/textInputEditTextEmail'
input_password_id = 'com.loginmodule.learning:id/textInputEditTextPassword'
input_confirm_password_id = 'com.loginmodule.learning:id/textInputEditTextConfirmPassword'
btn_register_id = 'com.loginmodule.learning:id/appCompatButtonRegister'
error_input_name_xpath = '/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout/android.widget.ScrollView/android.support.v7.widget.LinearLayoutCompat/TextInputLayout[1]/android.widget.LinearLayout/android.widget.TextView'
error_input_email_xpath = '/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout/android.widget.ScrollView/android.support.v7.widget.LinearLayoutCompat/TextInputLayout[2]/android.widget.LinearLayout/android.widget.TextView'
error_input_password_xpath = '/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout/android.widget.ScrollView/android.support.v7.widget.LinearLayoutCompat/TextInputLayout[3]/android.widget.LinearLayout/android.widget.TextView'
error_input_confirm_password_xpath = '/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout/android.widget.ScrollView/android.support.v7.widget.LinearLayoutCompat/TextInputLayout[4]/android.widget.LinearLayout/android.widget.TextView'
error_failed_register_id = 'com.loginmodule.learning:id/snackbar_text'
success_register_id = 'com.loginmodule.learning:id/snackbar_text'